name: Delete UAT release

# This is a GitHub action because Circle:CI doesn't see PR closed events
# but they are available to actions
on:
  # pull_request_target runs even when PRs have conflicts - pull_request does not
  # here we just want to tidy up regardless of the state of the PR.
  pull_request_target:
    types:
      - closed

jobs:
  delete_uat_job:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: Delete from STAGING namespace using target
        id: delete_uat
        uses: ./.github/actions/delete-uat-release
        with:
          k8s_cluster: ${{ secrets.FALA_K8S_CLUSTER_NAME }}
          k8s_cluster_cert: ${{ secrets.FALA_K8S_CLUSTER_CERT }}
          k8s_namespace: ${{ secrets.FALA_K8S_NAMESPACE }}
          k8s_token: ${{ secrets.FALA_K8S_TOKEN }}
      - name: Result
        shell: bash
        run: echo ${{ steps.delete_uat.outputs.delete-message }}\
